### PR TITLE
fix: fix windows create-app name for nuxt projects

### LINKED ISSUE #1066: Create-app for nuxt framework returns an error
### Describe the bug

Create-app returns an error for the nuxt framework.
image

### Tried
npx clear-npx-cache
npx formkit@next create-app --framework=nuxt --pro=**-*********** (Provided key is replaced with asterisks)
npx formkit@next create-app --framework=nuxt (without project key)

Looks like it also creates the folder `$APP_NAME` instead of the `formkit-app` that was specified in the cli wizard
image

### Environment

• Windows 10
• Chrome
• formkit@1.4.0 
• node@20.10.0

### PR DESCRIPTION
**Pull request by fenilli**
it fixes #1066 by using the interpolation for files instead of `$APP_NAME` that is unix specific.

it also adds a proccess.exit() for safe cancel after it finishes creation.

### CODE REVIEW

File: packages/cli/src/createApp.ts [hunk 1]
```diff
@@ -246,16 +246,23 @@ export async function createApp(
...
+      📁 cd ${appName}
+      ✅ npm install
+      🚀 npm run dev
+    `)
   } else {
     options.lang = 'ts'
     info('Fetching nuxi cli...')
     const subprocess = execaCommand(
-      `npx --yes nuxi@latest init --no-install $APP_NAME`,
+      `npx --yes nuxi@latest init --no-install ${appName}`,
```
Comment (justin-schroeder) [inline packages/cli/src/createApp.ts:261]: One issue here is that if the appName contains spaces this will not work properly. We could use quotes I suppose, or perhaps do some kind of escaping strategy

**Review by justin-schroeder — CHANGES_REQUESTED** [review]

File: packages/cli/src/createApp.ts (hunk 1 above)
Comment (fenilli) [reply packages/cli/src/createApp.ts]: The changes now make sure its surrounded by " so it works for names with space and folders.
